#!/bin/sh

# TODO rewrite?

set -eu

REF_NAME="${1}"
OLD_OBJECT="${2}"
NEW_OBJECT="${3}"

WORKDIR="$(mktemp -d)"
CACHE_DIR="/tmp/cache/${SOFT_SERVE_REPO_NAME}/${REF_NAME}"

echo "Repository: ${SOFT_SERVE_REPO_NAME}"
echo "Ref name: ${REF_NAME}"
echo "Old object: ${OLD_OBJECT}"
echo "New object: ${NEW_OBJECT}"
echo "Working directory: ${WORKDIR}"

git worktree add "${WORKDIR}" "${NEW_OBJECT}"

pushd "${WORKDIR}"

if [ ! -f "flake.nix" ] || [ ! -f "Makefile" ]; then
    echo "flake.nix or Makefile not found, skipping CI." >&2
else
    mkdir -p "${CACHE_DIR}"
    nix develop --command \
        make ci REF_NAME="${REF_NAME}" OLD_OBJECT="${OLD_OBJECT}" NEW_OBJECT="${NEW_OBJECT}" CACHE_DIR="${CACHE_DIR}"
fi

if [ ! -f "Dockerfile" ]; then
    echo "Dockerfile not found, skipping container build." >&2
else
    export REGISTRY_HOST="${REGISTRY_HOST:-docker.io}"

    # TODO docker login?
    docker build . \
        --tag "${REGISTRY_HOST}/${SOFT_SERVE_REPO_NAME}:latest" \
        --push
fi

popd

git worktree remove "$WORKDIR"
